export default {
  ADD_CHECKIN_REQUEST: '@checkin/ADD_CHECKIN_REQUEST',
  ADD_CHECKIN_SUCCESS: '@checkin/ADD_CHECKIN_SUCCESS',
  ADD_CHECKIN_FAILURE: '@checkin/ADD_CHECKIN_FAILURE',
  GET_CHECKINS_REQUEST: '@checkin/GET_CHECKINS_REQUEST',
  GET_CHECKINS_SUCCESS: '@checkin/GET_CHECKINS_SUCCESS',
  GET_CHECKINS_FAILURE: '@checkin/GET_CHECKINS_FAILURE',
};
