export default {
  ADD_HELP_ORDER_REQUEST: '@helpOrder/ADD_HELP_ORDER_REQUEST',
  ADD_HELP_ORDER_SUCCESS: '@helpOrder/ADD_HELP_ORDER_SUCCESS',
  ADD_HELP_ORDER_FAILURE: '@helpOrder/ADD_HELP_ORDER_FAILURE',
  GET_HELP_ORDERS_REQUEST: '@helpOrder/GET_HELP_ORDERS_REQUEST',
  GET_HELP_ORDERS_SUCCESS: '@helpOrder/GET_HELP_ORDERS_SUCCESS',
  GET_HELP_ORDERS_FAILURE: '@helpOrder/GET_HELP_ORDERS_FAILURE',
};
